// generated by StellarHeliosProject using Stellar Helios Rollup type-generator

import { HeliosScriptBundle } from "src/helios/HeliosScriptBundle.ts"   // todo import from @stellar-contracts
import { CapoHeliosBundle } from "src/CapoHeliosBundle.ts"                    // todo import from @stellar-contracts
import { StellarHeliosProject } from "src/helios/StellarHeliosProject.ts" // todo import from @stellar-contracts
import CapoMinterBundle from "src/minting/CapoMinter.hlbundle.js";
import UnspecializedDgtBundle from "src/delegation/UnspecializedDelegate.hlbundle.js";
import BundleMintDelegateWithGenericUuts from "tests/specialMintDelegate/uutMintingMintDelegate.hlbundle.js";
import withGenericUuts from "tests/withGenericUuts.hlbundle.js";

export const project = new StellarHeliosProject();

project.addBundle("src/minting/CapoMinter.hlbundle.js", CapoMinterBundle);
project.addBundle("src/delegation/UnspecializedDelegate.hlbundle.js", UnspecializedDgtBundle);
project.addBundle("tests/specialMintDelegate/uutMintingMintDelegate.hlbundle.js", BundleMintDelegateWithGenericUuts);
project.addBundle("tests/withGenericUuts.hlbundle.js", withGenericUuts);
