#!/bin/bash

if [[ -z $DEBUG ]] ; then
  node node_modules/rollup/dist/bin/rollup --config rollup.config.ts \
  --configPlugin 'esbuild={loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}' \
  $@
else
  node --inspect-brk node_modules/rollup/dist/bin/rollup --config rollup.config.ts \
  --configPlugin 'esbuild={loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}' \
  $@
fi
