// generated by Stellar Contracts dataBridgeGenerator
// based on types defined in BasicDelegate (src/delegation/BasicDelegate.hl)
// recommended: CHECK THIS FILE INTO YOUR VERSION CONTROL SYSTEM
//   ... and keep checking in the changes as your on-chain types evolve.
//
// NOTE: this file is auto-generated; do not edit directly

import { Cast } from "@helios-lang/contract-utils"
import type { UplcData } from "@helios-lang/uplc";
import type { 
    IntLike,
    ByteArrayLike,
 } from "@helios-lang/codec-utils";
import type {
    Address,
    AssetClass,
    DatumHash,
    MintingPolicyHash,
    PubKey,
    PubKeyHash,
    ScriptHash,
    SpendingCredential,
    StakingCredential,
    StakingHash,
    StakingValidatorHash,
    TimeRange,
    TxId,
    TxInput,
    TxOutput,
    TxOutputId,
    TxOutputDatum,
    ValidatorHash,
    Value,
} from "@helios-lang/ledger";
import type { EnumTypeSchema, StructTypeSchema } from "@helios-lang/type-utils";


import { DataBridge } from "../../helios/dataBridge/DataBridge.js"
import { 
    EnumBridge,
    type JustAnEnum,
} from "../../helios/dataBridge/EnumBridge.js"
import type { tagOnly } from "../../helios/HeliosScriptBundle.js"
import type {hasSeed, isActivity} from "../../StellarContract.js"

// todo: namespacing for all the good stuff here
// namespace uutMintingDelegateDataBridge {

import type {
    DelegationDetail, DelegationDetailLike,
    SampleStruct, SampleStructLike,
    SomeEnum$hasNestedFields, SomeEnum$hasNestedFieldsLike,
    SomeEnum$hasRecursiveFields, SomeEnum$hasRecursiveFieldsLike,
    SomeEnum, SomeEnumLike,
    DelegateDatum$MultiFieldVariant, DelegateDatum$MultiFieldVariantLike,
    DelegateDatum$MultiFieldNestedThings, DelegateDatum$MultiFieldNestedThingsLike,
    DelegateDatum, DelegateDatumLike,
    CapoLifecycleActivity$CreatingDelegate, CapoLifecycleActivity$CreatingDelegateLike,
    CapoLifecycleActivity, CapoLifecycleActivityLike,
    DelegateLifecycleActivity$ReplacingMe, DelegateLifecycleActivity$ReplacingMeLike,
    DelegateLifecycleActivity, DelegateLifecycleActivityLike,
    SpendingActivity, SpendingActivityLike,
    MintingActivity$mintingUuts, MintingActivity$mintingUutsLike,
    MintingActivity, MintingActivityLike,
    BurningActivity, BurningActivityLike,
    DelegateActivity$CreatingDelegatedData, DelegateActivity$CreatingDelegatedDataLike,
    DelegateActivity$UpdatingDelegatedData, DelegateActivity$UpdatingDelegatedDataLike,
    DelegateActivity$DeletingDelegatedData, DelegateActivity$DeletingDelegatedDataLike,
    DelegateActivity, DelegateActivityLike
} from "./uutMintingMintDelegate.typeInfo.js";

export type * as types from "./uutMintingMintDelegate.typeInfo.js";
import type * as types from "./uutMintingMintDelegate.typeInfo.js";



//Note about @ts-expect-error drilling through protected accessors: This 
//   allows the interface for the nested accessor to show only the public details,
//   while allowing us to collaborate between these two closely-related classes.
//   Like "friends" in C++.

/**
 * data bridge for BasicDelegate script (defined in BundleMintDelegateWithGenericUuts)}
 * main: src/delegation/BasicDelegate.hl, project: stellar-contracts
 * @remarks - note that you may override get dataBridgeName() { return "..." } to customize the name of this bridge class
 */
export class uutMintingDelegateDataBridge extends DataBridge {
    // for datum:
    datum: DelegateDatumHelper = new DelegateDatumHelper(this.bundle, {})   // datumAccessor/enum 
    DelegateDatum: DelegateDatumHelper = this.datum;
    readDatum = (d: UplcData) => {
        //@ts-expect-error drilling through the protected accessor.
        //   ... see more comments about that above
        return this.datum.__cast.fromUplcData(d);
    }


// for activity types:

    __activityCast = new Cast<
        DelegateActivity, DelegateActivityLike
    >(DelegateActivitySchema, { isMainnet: true }); // activityAccessorCast

    /**
     * generates UplcData for the activity type (DelegateActivity) for the BasicDelegate script
     */
    activity : DelegateActivityHelper= new DelegateActivityHelper(this.bundle, {isActivity: true}); // activityAccessor/enum
        DelegateActivity: DelegateActivityHelper = this.activity;


    types = {
        SomeEnum: new SomeEnumHelper(this.bundle),
        DelegateDatum: new DelegateDatumHelper(this.bundle),
        CapoLifecycleActivity: new CapoLifecycleActivityHelper(this.bundle),
        DelegateLifecycleActivity: new DelegateLifecycleActivityHelper(this.bundle),
        SpendingActivity: new SpendingActivityHelper(this.bundle),
        MintingActivity: new MintingActivityHelper(this.bundle),
        BurningActivity: new BurningActivityHelper(this.bundle),
        DelegateActivity: new DelegateActivityHelper(this.bundle),

        DelegationDetail: (fields: DelegationDetailLike | {
    capoAddr: /*minStructField*/ Address | string
    mph: /*minStructField*/ MintingPolicyHash | string | number[]
    tn: /*minStructField*/ number[]
}
) => {
        return this.__DelegationDetailCast.toUplcData(fields);
    },
        SampleStruct: (fields: SampleStructLike | {
    a: /*minStructField*/ IntLike
    b: /*minStructField*/ Map<string, number[]>
    c: /*minStructField*/ Array<boolean>
    d: /*minStructField*/ Option<UplcData>
}
) => {
        return this.__SampleStructCast.toUplcData(fields);
    },    }    

    __DelegationDetailCast = new Cast<
                DelegationDetail, DelegationDetailLike
            >(DelegationDetailSchema, { isMainnet: true });
    __SampleStructCast = new Cast<
                SampleStruct, SampleStructLike
            >(SampleStructSchema, { isMainnet: true });


}
export default uutMintingDelegateDataBridge;


/**
 * Helper class for generating UplcData for variants of the SomeEnum enum type.
 */
export class SomeEnumHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       SomeEnum,
       SomeEnumLike
   >(SomeEnumSchema, { isMainnet: true });

/**
 * (property getter): UplcData for "uutMintingDelegate::SomeEnum.justATag"
 */
    get justATag() {
        const uplc = this.mkUplcData({ justATag: {} }, 
            "uutMintingDelegate::SomeEnum.justATag");
       return uplc;
    } /* tagOnly variant accessor */

    justAnInt(
        m: IntLike
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           justAnInt: { m: m } 
        }, "uutMintingDelegate::SomeEnum.justAnInt"); /*SingleField enum variant*/
       return uplc;
    }

    oneNestedStruct(
        m: SampleStructLike
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           oneNestedStruct: { m: m } 
        }, "uutMintingDelegate::SomeEnum.oneNestedStruct"); /*SingleField enum variant*/
       return uplc;
    }

    /**
     * generates  UplcData for "uutMintingDelegate::SomeEnum.hasNestedFields"
     * @remarks - SomeEnum$hasNestedFieldsLike is the same as the expanded field-types.     */
    hasNestedFields(fields: SomeEnum$hasNestedFieldsLike | { 
        m: SampleStructLike,
        n: IntLike } ) : UplcData {
        const uplc = this.mkUplcData({
            hasNestedFields: fields 
        }, "uutMintingDelegate::SomeEnum.hasNestedFields");
       return uplc;
    } /*multiFieldVariant enum accessor*/

    /**
     * generates  UplcData for "uutMintingDelegate::SomeEnum.hasRecursiveFields"
     * @remarks - SomeEnum$hasRecursiveFieldsLike is the same as the expanded field-types.     */
    hasRecursiveFields(fields: SomeEnum$hasRecursiveFieldsLike | { 
        placeholder: IntLike,
        ph2: string } ) : UplcData {
        const uplc = this.mkUplcData({
            hasRecursiveFields: fields 
        }, "uutMintingDelegate::SomeEnum.hasRecursiveFields");
       return uplc;
    } /*multiFieldVariant enum accessor*/
}


/**
 * Helper class for generating UplcData for variants of the SomeEnum enum type.
 */
export class SomeEnumHelperNested extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       SomeEnum,
       SomeEnumLike
   >(SomeEnumSchema, { isMainnet: true });

/**
 * (property getter): UplcData for "uutMintingDelegate::SomeEnum.justATag"
 */
    get justATag() {
        const uplc = this.mkUplcData({ justATag: {} }, 
            "uutMintingDelegate::SomeEnum.justATag");
       return uplc;
    } /* tagOnly variant accessor */

    justAnInt(
        m: IntLike
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           justAnInt: { m: m } 
        }, "uutMintingDelegate::SomeEnum.justAnInt"); /*SingleField enum variant*/
       return uplc;
    }

    oneNestedStruct(
        m: SampleStructLike
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           oneNestedStruct: { m: m } 
        }, "uutMintingDelegate::SomeEnum.oneNestedStruct"); /*SingleField enum variant*/
       return uplc;
    }

    /**
     * generates  UplcData for "uutMintingDelegate::SomeEnum.hasNestedFields"
     * @remarks - SomeEnum$hasNestedFieldsLike is the same as the expanded field-types.     */
    hasNestedFields(fields: SomeEnum$hasNestedFieldsLike | { 
        m: SampleStructLike,
        n: IntLike } ) : UplcData {
        const uplc = this.mkUplcData({
            hasNestedFields: fields 
        }, "uutMintingDelegate::SomeEnum.hasNestedFields");
       return uplc;
    } /*multiFieldVariant enum accessor*/

    /**
     * generates  UplcData for "uutMintingDelegate::SomeEnum.hasRecursiveFields"
     * @remarks - SomeEnum$hasRecursiveFieldsLike is the same as the expanded field-types.     */
    hasRecursiveFields(fields: SomeEnum$hasRecursiveFieldsLike | { 
        placeholder: IntLike,
        ph2: string } ) : UplcData {
        const uplc = this.mkUplcData({
            hasRecursiveFields: fields 
        }, "uutMintingDelegate::SomeEnum.hasRecursiveFields");
       return uplc;
    } /*multiFieldVariant enum accessor*/
}


/**
 * Helper class for generating UplcData for variants of the DelegateDatum enum type.
 */
export class DelegateDatumHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       DelegateDatum,
       DelegateDatumLike
   >(DelegateDatumSchema, { isMainnet: true });

    IsDelegation(
        dd: DelegationDetailLike
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           IsDelegation: { dd: dd } 
        }, "uutMintingDelegate::DelegateDatum.IsDelegation"); /*SingleField enum variant*/
       return uplc;
    }

/**
 * (property getter): UplcData for "uutMintingDelegate::DelegateDatum.ScriptReference"
 */
    get ScriptReference() {
        const uplc = this.mkUplcData({ ScriptReference: {} }, 
            "uutMintingDelegate::DelegateDatum.ScriptReference");
       return uplc;
    } /* tagOnly variant accessor */

    SingleDataElement(
        aString: string
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           SingleDataElement: { aString: aString } 
        }, "uutMintingDelegate::DelegateDatum.SingleDataElement"); /*SingleField enum variant*/
       return uplc;
    }

    SingleNestedStruct(
        aStruct: SampleStructLike
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           SingleNestedStruct: { aStruct: aStruct } 
        }, "uutMintingDelegate::DelegateDatum.SingleNestedStruct"); /*SingleField enum variant*/
       return uplc;
    }

    get HasNestedEnum() {
        const nestedAccessor = new SomeEnumHelperNested(this.bundle,
            {isNested: true, isActivity: false 
        });
        //@ts-expect-error drilling through the protected accessor.  See more comments about that above
        nestedAccessor.mkDataVia((nested: SomeEnumLike) => {
           return  this.mkUplcData({ HasNestedEnum: { nested: nested } }, 
            "uutMintingDelegate::DelegateDatum.HasNestedEnum");
        });
        return nestedAccessor;
    } /* nested enum accessor */

    /**
     * generates  UplcData for "uutMintingDelegate::DelegateDatum.MultiFieldVariant"
     * @remarks - DelegateDatum$MultiFieldVariantLike is the same as the expanded field-types.     */
    MultiFieldVariant(fields: DelegateDatum$MultiFieldVariantLike | { 
        field1: IntLike,
        field2: string } ) : UplcData {
        const uplc = this.mkUplcData({
            MultiFieldVariant: fields 
        }, "uutMintingDelegate::DelegateDatum.MultiFieldVariant");
       return uplc;
    } /*multiFieldVariant enum accessor*/

    /**
     * generates  UplcData for "uutMintingDelegate::DelegateDatum.MultiFieldNestedThings"
     * @remarks - DelegateDatum$MultiFieldNestedThingsLike is the same as the expanded field-types.     */
    MultiFieldNestedThings(fields: DelegateDatum$MultiFieldNestedThingsLike | { 
        nestedStruct: SampleStructLike,
        nestedEnumMaybe: Option<
        | { justATag: /*minEnumVariant*/ tagOnly }
        | { justAnInt: /*minEnumVariant*/ { m: IntLike /*singleVariantField*/ }  }
        | { oneNestedStruct: /*minEnumVariant*/ { m: SampleStructLike /*singleVariantField*/ }  }
        | { hasNestedFields: /*minEnumVariant*/ SomeEnum$hasNestedFieldsLike }
        | { hasRecursiveFields: /*minEnumVariant*/ SomeEnum$hasRecursiveFieldsLike }> } ) : UplcData {
        const uplc = this.mkUplcData({
            MultiFieldNestedThings: fields 
        }, "uutMintingDelegate::DelegateDatum.MultiFieldNestedThings");
       return uplc;
    } /*multiFieldVariant enum accessor*/
}


/**
 * Helper class for generating UplcData for variants of the CapoLifecycleActivity enum type.
 */
export class CapoLifecycleActivityHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       CapoLifecycleActivity,
       CapoLifecycleActivityLike
   >(CapoLifecycleActivitySchema, { isMainnet: true });

    /**
     * generates  UplcData for "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    CreatingDelegate(value: hasSeed, fields: { 
        purpose: string 
    } ) : UplcData
    /**
    * generates UplcData for "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate" with raw seed details included in fields.
    */
    CreatingDelegate(fields: CapoLifecycleActivity$CreatingDelegateLike | {
            seed: TxOutputId | string,
            purpose: string
    } ): UplcData
    CreatingDelegate(
        seedOrUf: hasSeed | CapoLifecycleActivity$CreatingDelegateLike, 
        filteredFields?: { 
            purpose: string
    }) : UplcData {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                CreatingDelegate: { seed: seedTxOutputId, ...filteredFields } 
            }, "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate");
           return uplc;
        } else {
            const fields = seedOrUf as CapoLifecycleActivity$CreatingDelegateLike; 
           const uplc = this.mkUplcData({
                CreatingDelegate: fields 
            }, "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 

}


/**
 * Helper class for generating UplcData for variants of the DelegateLifecycleActivity enum type.
 */
export class DelegateLifecycleActivityHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       DelegateLifecycleActivity,
       DelegateLifecycleActivityLike
   >(DelegateLifecycleActivitySchema, { isMainnet: true });

    /**
     * generates  UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    ReplacingMe(value: hasSeed, fields: { 
        purpose: string 
    } ) : UplcData
    /**
    * generates UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe" with raw seed details included in fields.
    */
    ReplacingMe(fields: DelegateLifecycleActivity$ReplacingMeLike | {
            seed: TxOutputId | string,
            purpose: string
    } ): UplcData
    ReplacingMe(
        seedOrUf: hasSeed | DelegateLifecycleActivity$ReplacingMeLike, 
        filteredFields?: { 
            purpose: string
    }) : UplcData {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                ReplacingMe: { seed: seedTxOutputId, ...filteredFields } 
            }, "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe");
           return uplc;
        } else {
            const fields = seedOrUf as DelegateLifecycleActivity$ReplacingMeLike; 
           const uplc = this.mkUplcData({
                ReplacingMe: fields 
            }, "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 


/**
 * (property getter): UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.Retiring"
 */
    get Retiring() {
        const uplc = this.mkUplcData({ Retiring: {} }, 
            "CapoDelegateHelpers::DelegateLifecycleActivity.Retiring");
       return uplc;
    } /* tagOnly variant accessor */

/**
 * (property getter): UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.ValidatingSettings"
 */
    get ValidatingSettings() {
        const uplc = this.mkUplcData({ ValidatingSettings: {} }, 
            "CapoDelegateHelpers::DelegateLifecycleActivity.ValidatingSettings");
       return uplc;
    } /* tagOnly variant accessor */
}


/**
 * Helper class for generating UplcData for variants of the SpendingActivity enum type.
 */
export class SpendingActivityHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       SpendingActivity,
       SpendingActivityLike
   >(SpendingActivitySchema, { isMainnet: true });

    _placeholder2SA(
        id: number[]
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           _placeholder2SA: { id: id } 
        }, "uutMintingDelegate::SpendingActivity._placeholder2SA"); /*SingleField enum variant*/
       return uplc;
    }

    mockWorkingSpendActivity(
        id: number[]
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           mockWorkingSpendActivity: { id: id } 
        }, "uutMintingDelegate::SpendingActivity.mockWorkingSpendActivity"); /*SingleField enum variant*/
       return uplc;
    }
}


/**
 * Helper class for generating UplcData for variants of the MintingActivity enum type.
 */
export class MintingActivityHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       MintingActivity,
       MintingActivityLike
   >(MintingActivitySchema, { isMainnet: true });

    /**
     * generates  UplcData for "uutMintingDelegate::MintingActivity.mintingUuts", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    mintingUuts(value: hasSeed, fields: { 
        purposes: Array<string> 
    } ) : UplcData
    /**
    * generates UplcData for "uutMintingDelegate::MintingActivity.mintingUuts" with raw seed details included in fields.
    */
    mintingUuts(fields: MintingActivity$mintingUutsLike | {
            seed: TxOutputId | string,
            purposes: Array<string>
    } ): UplcData
    mintingUuts(
        seedOrUf: hasSeed | MintingActivity$mintingUutsLike, 
        filteredFields?: { 
            purposes: Array<string>
    }) : UplcData {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                mintingUuts: { seed: seedTxOutputId, ...filteredFields } 
            }, "uutMintingDelegate::MintingActivity.mintingUuts");
           return uplc;
        } else {
            const fields = seedOrUf as MintingActivity$mintingUutsLike; 
           const uplc = this.mkUplcData({
                mintingUuts: fields 
            }, "uutMintingDelegate::MintingActivity.mintingUuts");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 


/**
 * (property getter): UplcData for "uutMintingDelegate::MintingActivity.mockOtherActivity"
 */
    get mockOtherActivity() {
        const uplc = this.mkUplcData({ mockOtherActivity: {} }, 
            "uutMintingDelegate::MintingActivity.mockOtherActivity");
       return uplc;
    } /* tagOnly variant accessor */
}


/**
 * Helper class for generating UplcData for variants of the BurningActivity enum type.
 */
export class BurningActivityHelper extends EnumBridge<JustAnEnum> {
    protected __cast = new Cast<
       BurningActivity,
       BurningActivityLike
   >(BurningActivitySchema, { isMainnet: true });

    _placeholder2BA(
        recId: number[]
    ) : UplcData {
        const uplc = this.mkUplcData({ 
           _placeholder2BA: { recId: recId } 
        }, "uutMintingDelegate::BurningActivity._placeholder2BA"); /*SingleField enum variant*/
       return uplc;
    }
}


/**
 * Helper class for generating UplcData for variants of the CapoLifecycleActivity enum type.
 */
export class CapoLifecycleActivityHelperNested extends EnumBridge<isActivity> {
    protected __cast = new Cast<
       CapoLifecycleActivity,
       CapoLifecycleActivityLike
   >(CapoLifecycleActivitySchema, { isMainnet: true });

    /**
     * generates isActivity/redeemer wrapper with UplcData for "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    CreatingDelegate(value: hasSeed, fields: { 
        purpose: string 
    } ) : isActivity
    /**
    * generates UplcData for "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate" with raw seed details included in fields.
    */
    CreatingDelegate(fields: CapoLifecycleActivity$CreatingDelegateLike | {
            seed: TxOutputId | string,
            purpose: string
    } ): isActivity
    CreatingDelegate(
        seedOrUf: hasSeed | CapoLifecycleActivity$CreatingDelegateLike, 
        filteredFields?: { 
            purpose: string
    }) : isActivity {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                CreatingDelegate: { seed: seedTxOutputId, ...filteredFields } 
            }, "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate");
           return uplc;
        } else {
            const fields = seedOrUf as CapoLifecycleActivity$CreatingDelegateLike; 
           const uplc = this.mkUplcData({
                CreatingDelegate: fields 
            }, "CapoDelegateHelpers::CapoLifecycleActivity.CreatingDelegate");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 

}


/**
 * Helper class for generating UplcData for variants of the DelegateLifecycleActivity enum type.
 */
export class DelegateLifecycleActivityHelperNested extends EnumBridge<isActivity> {
    protected __cast = new Cast<
       DelegateLifecycleActivity,
       DelegateLifecycleActivityLike
   >(DelegateLifecycleActivitySchema, { isMainnet: true });

    /**
     * generates isActivity/redeemer wrapper with UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    ReplacingMe(value: hasSeed, fields: { 
        purpose: string 
    } ) : isActivity
    /**
    * generates UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe" with raw seed details included in fields.
    */
    ReplacingMe(fields: DelegateLifecycleActivity$ReplacingMeLike | {
            seed: TxOutputId | string,
            purpose: string
    } ): isActivity
    ReplacingMe(
        seedOrUf: hasSeed | DelegateLifecycleActivity$ReplacingMeLike, 
        filteredFields?: { 
            purpose: string
    }) : isActivity {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                ReplacingMe: { seed: seedTxOutputId, ...filteredFields } 
            }, "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe");
           return uplc;
        } else {
            const fields = seedOrUf as DelegateLifecycleActivity$ReplacingMeLike; 
           const uplc = this.mkUplcData({
                ReplacingMe: fields 
            }, "CapoDelegateHelpers::DelegateLifecycleActivity.ReplacingMe");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 


/**
 * (property getter): UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.Retiring"
 */
    get Retiring() {
        const uplc = this.mkUplcData({ Retiring: {} }, 
            "CapoDelegateHelpers::DelegateLifecycleActivity.Retiring");
       return uplc;
    } /* tagOnly variant accessor */

/**
 * (property getter): UplcData for "CapoDelegateHelpers::DelegateLifecycleActivity.ValidatingSettings"
 */
    get ValidatingSettings() {
        const uplc = this.mkUplcData({ ValidatingSettings: {} }, 
            "CapoDelegateHelpers::DelegateLifecycleActivity.ValidatingSettings");
       return uplc;
    } /* tagOnly variant accessor */
}


/**
 * Helper class for generating UplcData for variants of the SpendingActivity enum type.
 */
export class SpendingActivityHelperNested extends EnumBridge<isActivity> {
    protected __cast = new Cast<
       SpendingActivity,
       SpendingActivityLike
   >(SpendingActivitySchema, { isMainnet: true });

    _placeholder2SA(
        id: number[]
    ) : isActivity {
        const uplc = this.mkUplcData({ 
           _placeholder2SA: { id: id } 
        }, "uutMintingDelegate::SpendingActivity._placeholder2SA"); /*SingleField enum variant*/
       return uplc;
    }

    mockWorkingSpendActivity(
        id: number[]
    ) : isActivity {
        const uplc = this.mkUplcData({ 
           mockWorkingSpendActivity: { id: id } 
        }, "uutMintingDelegate::SpendingActivity.mockWorkingSpendActivity"); /*SingleField enum variant*/
       return uplc;
    }
}


/**
 * Helper class for generating UplcData for variants of the MintingActivity enum type.
 */
export class MintingActivityHelperNested extends EnumBridge<isActivity> {
    protected __cast = new Cast<
       MintingActivity,
       MintingActivityLike
   >(MintingActivitySchema, { isMainnet: true });

    /**
     * generates isActivity/redeemer wrapper with UplcData for "uutMintingDelegate::MintingActivity.mintingUuts", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    mintingUuts(value: hasSeed, fields: { 
        purposes: Array<string> 
    } ) : isActivity
    /**
    * generates UplcData for "uutMintingDelegate::MintingActivity.mintingUuts" with raw seed details included in fields.
    */
    mintingUuts(fields: MintingActivity$mintingUutsLike | {
            seed: TxOutputId | string,
            purposes: Array<string>
    } ): isActivity
    mintingUuts(
        seedOrUf: hasSeed | MintingActivity$mintingUutsLike, 
        filteredFields?: { 
            purposes: Array<string>
    }) : isActivity {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                mintingUuts: { seed: seedTxOutputId, ...filteredFields } 
            }, "uutMintingDelegate::MintingActivity.mintingUuts");
           return uplc;
        } else {
            const fields = seedOrUf as MintingActivity$mintingUutsLike; 
           const uplc = this.mkUplcData({
                mintingUuts: fields 
            }, "uutMintingDelegate::MintingActivity.mintingUuts");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 


/**
 * (property getter): UplcData for "uutMintingDelegate::MintingActivity.mockOtherActivity"
 */
    get mockOtherActivity() {
        const uplc = this.mkUplcData({ mockOtherActivity: {} }, 
            "uutMintingDelegate::MintingActivity.mockOtherActivity");
       return uplc;
    } /* tagOnly variant accessor */
}


/**
 * Helper class for generating UplcData for variants of the BurningActivity enum type.
 */
export class BurningActivityHelperNested extends EnumBridge<isActivity> {
    protected __cast = new Cast<
       BurningActivity,
       BurningActivityLike
   >(BurningActivitySchema, { isMainnet: true });

    _placeholder2BA(
        recId: number[]
    ) : isActivity {
        const uplc = this.mkUplcData({ 
           _placeholder2BA: { recId: recId } 
        }, "uutMintingDelegate::BurningActivity._placeholder2BA"); /*SingleField enum variant*/
       return uplc;
    }
}


/**
 * Helper class for generating UplcData for variants of the DelegateActivity enum type.
 */
export class DelegateActivityHelper extends EnumBridge<isActivity> {
    protected __cast = new Cast<
       DelegateActivity,
       DelegateActivityLike
   >(DelegateActivitySchema, { isMainnet: true });

    get CapoLifecycleActivities() {
        const nestedAccessor = new CapoLifecycleActivityHelperNested(this.bundle,
            {isNested: true, isActivity: true 
        });
        //@ts-expect-error drilling through the protected accessor.  See more comments about that above
        nestedAccessor.mkDataVia((nested: CapoLifecycleActivityLike) => {
           return  this.mkUplcData({ CapoLifecycleActivities: { activity: nested } }, 
            "uutMintingDelegate::DelegateActivity.CapoLifecycleActivities");
        });
        return nestedAccessor;
    } /* nested enum accessor */

    get DelegateLifecycleActivities() {
        const nestedAccessor = new DelegateLifecycleActivityHelperNested(this.bundle,
            {isNested: true, isActivity: true 
        });
        //@ts-expect-error drilling through the protected accessor.  See more comments about that above
        nestedAccessor.mkDataVia((nested: DelegateLifecycleActivityLike) => {
           return  this.mkUplcData({ DelegateLifecycleActivities: { activity: nested } }, 
            "uutMintingDelegate::DelegateActivity.DelegateLifecycleActivities");
        });
        return nestedAccessor;
    } /* nested enum accessor */

    get SpendingActivities() {
        const nestedAccessor = new SpendingActivityHelperNested(this.bundle,
            {isNested: true, isActivity: true 
        });
        //@ts-expect-error drilling through the protected accessor.  See more comments about that above
        nestedAccessor.mkDataVia((nested: SpendingActivityLike) => {
           return  this.mkUplcData({ SpendingActivities: { activity: nested } }, 
            "uutMintingDelegate::DelegateActivity.SpendingActivities");
        });
        return nestedAccessor;
    } /* nested enum accessor */

    get MintingActivities() {
        const nestedAccessor = new MintingActivityHelperNested(this.bundle,
            {isNested: true, isActivity: true 
        });
        //@ts-expect-error drilling through the protected accessor.  See more comments about that above
        nestedAccessor.mkDataVia((nested: MintingActivityLike) => {
           return  this.mkUplcData({ MintingActivities: { activity: nested } }, 
            "uutMintingDelegate::DelegateActivity.MintingActivities");
        });
        return nestedAccessor;
    } /* nested enum accessor */

    get BurningActivities() {
        const nestedAccessor = new BurningActivityHelperNested(this.bundle,
            {isNested: true, isActivity: true 
        });
        //@ts-expect-error drilling through the protected accessor.  See more comments about that above
        nestedAccessor.mkDataVia((nested: BurningActivityLike) => {
           return  this.mkUplcData({ BurningActivities: { activity: nested } }, 
            "uutMintingDelegate::DelegateActivity.BurningActivities");
        });
        return nestedAccessor;
    } /* nested enum accessor */

    /**
     * generates isActivity/redeemer wrapper with UplcData for "uutMintingDelegate::DelegateActivity.CreatingDelegatedData", given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    CreatingDelegatedData(value: hasSeed, fields: { 
        dataType: string 
    } ) : isActivity
    /**
    * generates UplcData for "uutMintingDelegate::DelegateActivity.CreatingDelegatedData" with raw seed details included in fields.
    */
    CreatingDelegatedData(fields: DelegateActivity$CreatingDelegatedDataLike | {
            seed: TxOutputId | string,
            dataType: string
    } ): isActivity
    CreatingDelegatedData(
        seedOrUf: hasSeed | DelegateActivity$CreatingDelegatedDataLike, 
        filteredFields?: { 
            dataType: string
    }) : isActivity {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            const uplc = this.mkUplcData({
                CreatingDelegatedData: { seed: seedTxOutputId, ...filteredFields } 
            }, "uutMintingDelegate::DelegateActivity.CreatingDelegatedData");
           return uplc;
        } else {
            const fields = seedOrUf as DelegateActivity$CreatingDelegatedDataLike; 
           const uplc = this.mkUplcData({
                CreatingDelegatedData: fields 
            }, "uutMintingDelegate::DelegateActivity.CreatingDelegatedData");
           return uplc;
        }
    } /*multiFieldVariant/seeded enum accessor*/ 


    /**
     * generates isActivity/redeemer wrapper with UplcData for "uutMintingDelegate::DelegateActivity.UpdatingDelegatedData"
     * @remarks - DelegateActivity$UpdatingDelegatedDataLike is the same as the expanded field-types.     */
    UpdatingDelegatedData(fields: DelegateActivity$UpdatingDelegatedDataLike | { 
        dataType: string,
        recId: number[] } ) : isActivity {
        const uplc = this.mkUplcData({
            UpdatingDelegatedData: fields 
        }, "uutMintingDelegate::DelegateActivity.UpdatingDelegatedData");
       return uplc;
    } /*multiFieldVariant enum accessor*/

    /**
     * generates isActivity/redeemer wrapper with UplcData for "uutMintingDelegate::DelegateActivity.DeletingDelegatedData"
     * @remarks - DelegateActivity$DeletingDelegatedDataLike is the same as the expanded field-types.     */
    DeletingDelegatedData(fields: DelegateActivity$DeletingDelegatedDataLike | { 
        dataType: string,
        recId: number[] } ) : isActivity {
        const uplc = this.mkUplcData({
            DeletingDelegatedData: fields 
        }, "uutMintingDelegate::DelegateActivity.DeletingDelegatedData");
       return uplc;
    } /*multiFieldVariant enum accessor*/

    MultipleDelegateActivities(
        activities: Array<UplcData>
    ) : isActivity {
        const uplc = this.mkUplcData({ 
           MultipleDelegateActivities: { activities: activities } 
        }, "uutMintingDelegate::DelegateActivity.MultipleDelegateActivities"); /*SingleField enum variant*/
       return uplc;
    }
}


export const DelegationDetailSchema : StructTypeSchema = {
    "kind": "struct",
    "format": "list",
    "id": "__module__CapoDelegateHelpers__DelegationDetail[]",
    "name": "DelegationDetail",
    "fieldTypes": [
        {
            "name": "capoAddr",
            "type": {
                "kind": "internal",
                "name": "Address"
            }
        },
        {
            "name": "mph",
            "type": {
                "kind": "internal",
                "name": "MintingPolicyHash"
            }
        },
        {
            "name": "tn",
            "type": {
                "kind": "internal",
                "name": "ByteArray"
            }
        }
    ]
};

export const SampleStructSchema : StructTypeSchema = {
    "kind": "struct",
    "format": "list",
    "id": "__module__uutMintingDelegate__SampleStruct[]",
    "name": "SampleStruct",
    "fieldTypes": [
        {
            "name": "a",
            "type": {
                "kind": "internal",
                "name": "Int"
            }
        },
        {
            "name": "b",
            "type": {
                "kind": "map",
                "keyType": {
                    "kind": "internal",
                    "name": "String"
                },
                "valueType": {
                    "kind": "internal",
                    "name": "ByteArray"
                }
            }
        },
        {
            "name": "c",
            "type": {
                "kind": "list",
                "itemType": {
                    "kind": "internal",
                    "name": "Bool"
                }
            }
        },
        {
            "name": "d",
            "type": {
                "kind": "option",
                "someType": {
                    "kind": "internal",
                    "name": "Data"
                }
            }
        }
    ]
};

export const SomeEnumSchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "SomeEnum",
    "id": "__module__uutMintingDelegate__SomeEnum[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__uutMintingDelegate__SomeEnum[]__justATag",
            "name": "justATag",
            "fieldTypes": []
        },
        {
            "kind": "variant",
            "tag": 1,
            "id": "__module__uutMintingDelegate__SomeEnum[]__justAnInt",
            "name": "justAnInt",
            "fieldTypes": [
                {
                    "name": "m",
                    "type": {
                        "kind": "internal",
                        "name": "Int"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 2,
            "id": "__module__uutMintingDelegate__SomeEnum[]__oneNestedStruct",
            "name": "oneNestedStruct",
            "fieldTypes": [
                {
                    "name": "m",
                    "type": {
                        "kind": "struct",
                        "format": "list",
                        "id": "__module__uutMintingDelegate__SampleStruct[]",
                        "name": "SampleStruct",
                        "fieldTypes": [
                            {
                                "name": "a",
                                "type": {
                                    "kind": "internal",
                                    "name": "Int"
                                }
                            },
                            {
                                "name": "b",
                                "type": {
                                    "kind": "map",
                                    "keyType": {
                                        "kind": "internal",
                                        "name": "String"
                                    },
                                    "valueType": {
                                        "kind": "internal",
                                        "name": "ByteArray"
                                    }
                                }
                            },
                            {
                                "name": "c",
                                "type": {
                                    "kind": "list",
                                    "itemType": {
                                        "kind": "internal",
                                        "name": "Bool"
                                    }
                                }
                            },
                            {
                                "name": "d",
                                "type": {
                                    "kind": "option",
                                    "someType": {
                                        "kind": "internal",
                                        "name": "Data"
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 3,
            "id": "__module__uutMintingDelegate__SomeEnum[]__hasNestedFields",
            "name": "hasNestedFields",
            "fieldTypes": [
                {
                    "name": "m",
                    "type": {
                        "kind": "struct",
                        "format": "list",
                        "id": "__module__uutMintingDelegate__SampleStruct[]",
                        "name": "SampleStruct",
                        "fieldTypes": [
                            {
                                "name": "a",
                                "type": {
                                    "kind": "internal",
                                    "name": "Int"
                                }
                            },
                            {
                                "name": "b",
                                "type": {
                                    "kind": "map",
                                    "keyType": {
                                        "kind": "internal",
                                        "name": "String"
                                    },
                                    "valueType": {
                                        "kind": "internal",
                                        "name": "ByteArray"
                                    }
                                }
                            },
                            {
                                "name": "c",
                                "type": {
                                    "kind": "list",
                                    "itemType": {
                                        "kind": "internal",
                                        "name": "Bool"
                                    }
                                }
                            },
                            {
                                "name": "d",
                                "type": {
                                    "kind": "option",
                                    "someType": {
                                        "kind": "internal",
                                        "name": "Data"
                                    }
                                }
                            }
                        ]
                    }
                },
                {
                    "name": "n",
                    "type": {
                        "kind": "internal",
                        "name": "Int"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 4,
            "id": "__module__uutMintingDelegate__SomeEnum[]__hasRecursiveFields",
            "name": "hasRecursiveFields",
            "fieldTypes": [
                {
                    "name": "placeholder",
                    "type": {
                        "kind": "internal",
                        "name": "Int"
                    }
                },
                {
                    "name": "ph2",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                }
            ]
        }
    ]
};

export const DelegateDatumSchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "DelegateDatum",
    "id": "__module__uutMintingDelegate__DelegateDatum[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__IsDelegation",
            "name": "IsDelegation",
            "fieldTypes": [
                {
                    "name": "dd",
                    "type": {
                        "kind": "struct",
                        "format": "list",
                        "id": "__module__CapoDelegateHelpers__DelegationDetail[]",
                        "name": "DelegationDetail",
                        "fieldTypes": [
                            {
                                "name": "capoAddr",
                                "type": {
                                    "kind": "internal",
                                    "name": "Address"
                                }
                            },
                            {
                                "name": "mph",
                                "type": {
                                    "kind": "internal",
                                    "name": "MintingPolicyHash"
                                }
                            },
                            {
                                "name": "tn",
                                "type": {
                                    "kind": "internal",
                                    "name": "ByteArray"
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 1,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__ScriptReference",
            "name": "ScriptReference",
            "fieldTypes": []
        },
        {
            "kind": "variant",
            "tag": 2,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__SingleDataElement",
            "name": "SingleDataElement",
            "fieldTypes": [
                {
                    "name": "aString",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 3,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__SingleNestedStruct",
            "name": "SingleNestedStruct",
            "fieldTypes": [
                {
                    "name": "aStruct",
                    "type": {
                        "kind": "struct",
                        "format": "list",
                        "id": "__module__uutMintingDelegate__SampleStruct[]",
                        "name": "SampleStruct",
                        "fieldTypes": [
                            {
                                "name": "a",
                                "type": {
                                    "kind": "internal",
                                    "name": "Int"
                                }
                            },
                            {
                                "name": "b",
                                "type": {
                                    "kind": "map",
                                    "keyType": {
                                        "kind": "internal",
                                        "name": "String"
                                    },
                                    "valueType": {
                                        "kind": "internal",
                                        "name": "ByteArray"
                                    }
                                }
                            },
                            {
                                "name": "c",
                                "type": {
                                    "kind": "list",
                                    "itemType": {
                                        "kind": "internal",
                                        "name": "Bool"
                                    }
                                }
                            },
                            {
                                "name": "d",
                                "type": {
                                    "kind": "option",
                                    "someType": {
                                        "kind": "internal",
                                        "name": "Data"
                                    }
                                }
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 4,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__HasNestedEnum",
            "name": "HasNestedEnum",
            "fieldTypes": [
                {
                    "name": "nested",
                    "type": {
                        "kind": "enum",
                        "name": "SomeEnum",
                        "id": "__module__uutMintingDelegate__SomeEnum[]",
                        "variantTypes": [
                            {
                                "kind": "variant",
                                "tag": 0,
                                "id": "__module__uutMintingDelegate__SomeEnum[]__justATag",
                                "name": "justATag",
                                "fieldTypes": []
                            },
                            {
                                "kind": "variant",
                                "tag": 1,
                                "id": "__module__uutMintingDelegate__SomeEnum[]__justAnInt",
                                "name": "justAnInt",
                                "fieldTypes": [
                                    {
                                        "name": "m",
                                        "type": {
                                            "kind": "internal",
                                            "name": "Int"
                                        }
                                    }
                                ]
                            },
                            {
                                "kind": "variant",
                                "tag": 2,
                                "id": "__module__uutMintingDelegate__SomeEnum[]__oneNestedStruct",
                                "name": "oneNestedStruct",
                                "fieldTypes": [
                                    {
                                        "name": "m",
                                        "type": {
                                            "kind": "struct",
                                            "format": "list",
                                            "id": "__module__uutMintingDelegate__SampleStruct[]",
                                            "name": "SampleStruct",
                                            "fieldTypes": [
                                                {
                                                    "name": "a",
                                                    "type": {
                                                        "kind": "internal",
                                                        "name": "Int"
                                                    }
                                                },
                                                {
                                                    "name": "b",
                                                    "type": {
                                                        "kind": "map",
                                                        "keyType": {
                                                            "kind": "internal",
                                                            "name": "String"
                                                        },
                                                        "valueType": {
                                                            "kind": "internal",
                                                            "name": "ByteArray"
                                                        }
                                                    }
                                                },
                                                {
                                                    "name": "c",
                                                    "type": {
                                                        "kind": "list",
                                                        "itemType": {
                                                            "kind": "internal",
                                                            "name": "Bool"
                                                        }
                                                    }
                                                },
                                                {
                                                    "name": "d",
                                                    "type": {
                                                        "kind": "option",
                                                        "someType": {
                                                            "kind": "internal",
                                                            "name": "Data"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                ]
                            },
                            {
                                "kind": "variant",
                                "tag": 3,
                                "id": "__module__uutMintingDelegate__SomeEnum[]__hasNestedFields",
                                "name": "hasNestedFields",
                                "fieldTypes": [
                                    {
                                        "name": "m",
                                        "type": {
                                            "kind": "struct",
                                            "format": "list",
                                            "id": "__module__uutMintingDelegate__SampleStruct[]",
                                            "name": "SampleStruct",
                                            "fieldTypes": [
                                                {
                                                    "name": "a",
                                                    "type": {
                                                        "kind": "internal",
                                                        "name": "Int"
                                                    }
                                                },
                                                {
                                                    "name": "b",
                                                    "type": {
                                                        "kind": "map",
                                                        "keyType": {
                                                            "kind": "internal",
                                                            "name": "String"
                                                        },
                                                        "valueType": {
                                                            "kind": "internal",
                                                            "name": "ByteArray"
                                                        }
                                                    }
                                                },
                                                {
                                                    "name": "c",
                                                    "type": {
                                                        "kind": "list",
                                                        "itemType": {
                                                            "kind": "internal",
                                                            "name": "Bool"
                                                        }
                                                    }
                                                },
                                                {
                                                    "name": "d",
                                                    "type": {
                                                        "kind": "option",
                                                        "someType": {
                                                            "kind": "internal",
                                                            "name": "Data"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    },
                                    {
                                        "name": "n",
                                        "type": {
                                            "kind": "internal",
                                            "name": "Int"
                                        }
                                    }
                                ]
                            },
                            {
                                "kind": "variant",
                                "tag": 4,
                                "id": "__module__uutMintingDelegate__SomeEnum[]__hasRecursiveFields",
                                "name": "hasRecursiveFields",
                                "fieldTypes": [
                                    {
                                        "name": "placeholder",
                                        "type": {
                                            "kind": "internal",
                                            "name": "Int"
                                        }
                                    },
                                    {
                                        "name": "ph2",
                                        "type": {
                                            "kind": "internal",
                                            "name": "String"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 5,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__MultiFieldVariant",
            "name": "MultiFieldVariant",
            "fieldTypes": [
                {
                    "name": "field1",
                    "type": {
                        "kind": "internal",
                        "name": "Int"
                    }
                },
                {
                    "name": "field2",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 6,
            "id": "__module__uutMintingDelegate__DelegateDatum[]__MultiFieldNestedThings",
            "name": "MultiFieldNestedThings",
            "fieldTypes": [
                {
                    "name": "nestedStruct",
                    "type": {
                        "kind": "struct",
                        "format": "list",
                        "id": "__module__uutMintingDelegate__SampleStruct[]",
                        "name": "SampleStruct",
                        "fieldTypes": [
                            {
                                "name": "a",
                                "type": {
                                    "kind": "internal",
                                    "name": "Int"
                                }
                            },
                            {
                                "name": "b",
                                "type": {
                                    "kind": "map",
                                    "keyType": {
                                        "kind": "internal",
                                        "name": "String"
                                    },
                                    "valueType": {
                                        "kind": "internal",
                                        "name": "ByteArray"
                                    }
                                }
                            },
                            {
                                "name": "c",
                                "type": {
                                    "kind": "list",
                                    "itemType": {
                                        "kind": "internal",
                                        "name": "Bool"
                                    }
                                }
                            },
                            {
                                "name": "d",
                                "type": {
                                    "kind": "option",
                                    "someType": {
                                        "kind": "internal",
                                        "name": "Data"
                                    }
                                }
                            }
                        ]
                    }
                },
                {
                    "name": "nestedEnumMaybe",
                    "type": {
                        "kind": "option",
                        "someType": {
                            "kind": "enum",
                            "name": "SomeEnum",
                            "id": "__module__uutMintingDelegate__SomeEnum[]",
                            "variantTypes": [
                                {
                                    "kind": "variant",
                                    "tag": 0,
                                    "id": "__module__uutMintingDelegate__SomeEnum[]__justATag",
                                    "name": "justATag",
                                    "fieldTypes": []
                                },
                                {
                                    "kind": "variant",
                                    "tag": 1,
                                    "id": "__module__uutMintingDelegate__SomeEnum[]__justAnInt",
                                    "name": "justAnInt",
                                    "fieldTypes": [
                                        {
                                            "name": "m",
                                            "type": {
                                                "kind": "internal",
                                                "name": "Int"
                                            }
                                        }
                                    ]
                                },
                                {
                                    "kind": "variant",
                                    "tag": 2,
                                    "id": "__module__uutMintingDelegate__SomeEnum[]__oneNestedStruct",
                                    "name": "oneNestedStruct",
                                    "fieldTypes": [
                                        {
                                            "name": "m",
                                            "type": {
                                                "kind": "struct",
                                                "format": "list",
                                                "id": "__module__uutMintingDelegate__SampleStruct[]",
                                                "name": "SampleStruct",
                                                "fieldTypes": [
                                                    {
                                                        "name": "a",
                                                        "type": {
                                                            "kind": "internal",
                                                            "name": "Int"
                                                        }
                                                    },
                                                    {
                                                        "name": "b",
                                                        "type": {
                                                            "kind": "map",
                                                            "keyType": {
                                                                "kind": "internal",
                                                                "name": "String"
                                                            },
                                                            "valueType": {
                                                                "kind": "internal",
                                                                "name": "ByteArray"
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "name": "c",
                                                        "type": {
                                                            "kind": "list",
                                                            "itemType": {
                                                                "kind": "internal",
                                                                "name": "Bool"
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "name": "d",
                                                        "type": {
                                                            "kind": "option",
                                                            "someType": {
                                                                "kind": "internal",
                                                                "name": "Data"
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        }
                                    ]
                                },
                                {
                                    "kind": "variant",
                                    "tag": 3,
                                    "id": "__module__uutMintingDelegate__SomeEnum[]__hasNestedFields",
                                    "name": "hasNestedFields",
                                    "fieldTypes": [
                                        {
                                            "name": "m",
                                            "type": {
                                                "kind": "struct",
                                                "format": "list",
                                                "id": "__module__uutMintingDelegate__SampleStruct[]",
                                                "name": "SampleStruct",
                                                "fieldTypes": [
                                                    {
                                                        "name": "a",
                                                        "type": {
                                                            "kind": "internal",
                                                            "name": "Int"
                                                        }
                                                    },
                                                    {
                                                        "name": "b",
                                                        "type": {
                                                            "kind": "map",
                                                            "keyType": {
                                                                "kind": "internal",
                                                                "name": "String"
                                                            },
                                                            "valueType": {
                                                                "kind": "internal",
                                                                "name": "ByteArray"
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "name": "c",
                                                        "type": {
                                                            "kind": "list",
                                                            "itemType": {
                                                                "kind": "internal",
                                                                "name": "Bool"
                                                            }
                                                        }
                                                    },
                                                    {
                                                        "name": "d",
                                                        "type": {
                                                            "kind": "option",
                                                            "someType": {
                                                                "kind": "internal",
                                                                "name": "Data"
                                                            }
                                                        }
                                                    }
                                                ]
                                            }
                                        },
                                        {
                                            "name": "n",
                                            "type": {
                                                "kind": "internal",
                                                "name": "Int"
                                            }
                                        }
                                    ]
                                },
                                {
                                    "kind": "variant",
                                    "tag": 4,
                                    "id": "__module__uutMintingDelegate__SomeEnum[]__hasRecursiveFields",
                                    "name": "hasRecursiveFields",
                                    "fieldTypes": [
                                        {
                                            "name": "placeholder",
                                            "type": {
                                                "kind": "internal",
                                                "name": "Int"
                                            }
                                        },
                                        {
                                            "name": "ph2",
                                            "type": {
                                                "kind": "internal",
                                                "name": "String"
                                            }
                                        }
                                    ]
                                }
                            ]
                        }
                    }
                }
            ]
        }
    ]
};

export const CapoLifecycleActivitySchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "CapoLifecycleActivity",
    "id": "__module__CapoDelegateHelpers__CapoLifecycleActivity[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__CapoDelegateHelpers__CapoLifecycleActivity[]__CreatingDelegate",
            "name": "CreatingDelegate",
            "fieldTypes": [
                {
                    "name": "seed",
                    "type": {
                        "kind": "internal",
                        "name": "TxOutputId"
                    }
                },
                {
                    "name": "purpose",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                }
            ]
        }
    ]
};

export const DelegateLifecycleActivitySchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "DelegateLifecycleActivity",
    "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]__ReplacingMe",
            "name": "ReplacingMe",
            "fieldTypes": [
                {
                    "name": "seed",
                    "type": {
                        "kind": "internal",
                        "name": "TxOutputId"
                    }
                },
                {
                    "name": "purpose",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 1,
            "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]__Retiring",
            "name": "Retiring",
            "fieldTypes": []
        },
        {
            "kind": "variant",
            "tag": 2,
            "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]__ValidatingSettings",
            "name": "ValidatingSettings",
            "fieldTypes": []
        }
    ]
};

export const SpendingActivitySchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "SpendingActivity",
    "id": "__module__uutMintingDelegate__SpendingActivity[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__uutMintingDelegate__SpendingActivity[]___placeholder2SA",
            "name": "_placeholder2SA",
            "fieldTypes": [
                {
                    "name": "id",
                    "type": {
                        "kind": "internal",
                        "name": "ByteArray"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 1,
            "id": "__module__uutMintingDelegate__SpendingActivity[]__mockWorkingSpendActivity",
            "name": "mockWorkingSpendActivity",
            "fieldTypes": [
                {
                    "name": "id",
                    "type": {
                        "kind": "internal",
                        "name": "ByteArray"
                    }
                }
            ]
        }
    ]
};

export const MintingActivitySchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "MintingActivity",
    "id": "__module__uutMintingDelegate__MintingActivity[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__uutMintingDelegate__MintingActivity[]__mintingUuts",
            "name": "mintingUuts",
            "fieldTypes": [
                {
                    "name": "seed",
                    "type": {
                        "kind": "internal",
                        "name": "TxOutputId"
                    }
                },
                {
                    "name": "purposes",
                    "type": {
                        "kind": "list",
                        "itemType": {
                            "kind": "internal",
                            "name": "String"
                        }
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 1,
            "id": "__module__uutMintingDelegate__MintingActivity[]__mockOtherActivity",
            "name": "mockOtherActivity",
            "fieldTypes": []
        }
    ]
};

export const BurningActivitySchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "BurningActivity",
    "id": "__module__uutMintingDelegate__BurningActivity[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__uutMintingDelegate__BurningActivity[]___placeholder2BA",
            "name": "_placeholder2BA",
            "fieldTypes": [
                {
                    "name": "recId",
                    "type": {
                        "kind": "internal",
                        "name": "ByteArray"
                    }
                }
            ]
        }
    ]
};

export const DelegateActivitySchema : EnumTypeSchema = {
    "kind": "enum",
    "name": "DelegateActivity",
    "id": "__module__uutMintingDelegate__DelegateActivity[]",
    "variantTypes": [
        {
            "kind": "variant",
            "tag": 0,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__CapoLifecycleActivities",
            "name": "CapoLifecycleActivities",
            "fieldTypes": [
                {
                    "name": "activity",
                    "type": {
                        "kind": "enum",
                        "name": "CapoLifecycleActivity",
                        "id": "__module__CapoDelegateHelpers__CapoLifecycleActivity[]",
                        "variantTypes": [
                            {
                                "kind": "variant",
                                "tag": 0,
                                "id": "__module__CapoDelegateHelpers__CapoLifecycleActivity[]__CreatingDelegate",
                                "name": "CreatingDelegate",
                                "fieldTypes": [
                                    {
                                        "name": "seed",
                                        "type": {
                                            "kind": "internal",
                                            "name": "TxOutputId"
                                        }
                                    },
                                    {
                                        "name": "purpose",
                                        "type": {
                                            "kind": "internal",
                                            "name": "String"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 1,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__DelegateLifecycleActivities",
            "name": "DelegateLifecycleActivities",
            "fieldTypes": [
                {
                    "name": "activity",
                    "type": {
                        "kind": "enum",
                        "name": "DelegateLifecycleActivity",
                        "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]",
                        "variantTypes": [
                            {
                                "kind": "variant",
                                "tag": 0,
                                "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]__ReplacingMe",
                                "name": "ReplacingMe",
                                "fieldTypes": [
                                    {
                                        "name": "seed",
                                        "type": {
                                            "kind": "internal",
                                            "name": "TxOutputId"
                                        }
                                    },
                                    {
                                        "name": "purpose",
                                        "type": {
                                            "kind": "internal",
                                            "name": "String"
                                        }
                                    }
                                ]
                            },
                            {
                                "kind": "variant",
                                "tag": 1,
                                "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]__Retiring",
                                "name": "Retiring",
                                "fieldTypes": []
                            },
                            {
                                "kind": "variant",
                                "tag": 2,
                                "id": "__module__CapoDelegateHelpers__DelegateLifecycleActivity[]__ValidatingSettings",
                                "name": "ValidatingSettings",
                                "fieldTypes": []
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 2,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__SpendingActivities",
            "name": "SpendingActivities",
            "fieldTypes": [
                {
                    "name": "activity",
                    "type": {
                        "kind": "enum",
                        "name": "SpendingActivity",
                        "id": "__module__uutMintingDelegate__SpendingActivity[]",
                        "variantTypes": [
                            {
                                "kind": "variant",
                                "tag": 0,
                                "id": "__module__uutMintingDelegate__SpendingActivity[]___placeholder2SA",
                                "name": "_placeholder2SA",
                                "fieldTypes": [
                                    {
                                        "name": "id",
                                        "type": {
                                            "kind": "internal",
                                            "name": "ByteArray"
                                        }
                                    }
                                ]
                            },
                            {
                                "kind": "variant",
                                "tag": 1,
                                "id": "__module__uutMintingDelegate__SpendingActivity[]__mockWorkingSpendActivity",
                                "name": "mockWorkingSpendActivity",
                                "fieldTypes": [
                                    {
                                        "name": "id",
                                        "type": {
                                            "kind": "internal",
                                            "name": "ByteArray"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 3,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__MintingActivities",
            "name": "MintingActivities",
            "fieldTypes": [
                {
                    "name": "activity",
                    "type": {
                        "kind": "enum",
                        "name": "MintingActivity",
                        "id": "__module__uutMintingDelegate__MintingActivity[]",
                        "variantTypes": [
                            {
                                "kind": "variant",
                                "tag": 0,
                                "id": "__module__uutMintingDelegate__MintingActivity[]__mintingUuts",
                                "name": "mintingUuts",
                                "fieldTypes": [
                                    {
                                        "name": "seed",
                                        "type": {
                                            "kind": "internal",
                                            "name": "TxOutputId"
                                        }
                                    },
                                    {
                                        "name": "purposes",
                                        "type": {
                                            "kind": "list",
                                            "itemType": {
                                                "kind": "internal",
                                                "name": "String"
                                            }
                                        }
                                    }
                                ]
                            },
                            {
                                "kind": "variant",
                                "tag": 1,
                                "id": "__module__uutMintingDelegate__MintingActivity[]__mockOtherActivity",
                                "name": "mockOtherActivity",
                                "fieldTypes": []
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 4,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__BurningActivities",
            "name": "BurningActivities",
            "fieldTypes": [
                {
                    "name": "activity",
                    "type": {
                        "kind": "enum",
                        "name": "BurningActivity",
                        "id": "__module__uutMintingDelegate__BurningActivity[]",
                        "variantTypes": [
                            {
                                "kind": "variant",
                                "tag": 0,
                                "id": "__module__uutMintingDelegate__BurningActivity[]___placeholder2BA",
                                "name": "_placeholder2BA",
                                "fieldTypes": [
                                    {
                                        "name": "recId",
                                        "type": {
                                            "kind": "internal",
                                            "name": "ByteArray"
                                        }
                                    }
                                ]
                            }
                        ]
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 5,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__CreatingDelegatedData",
            "name": "CreatingDelegatedData",
            "fieldTypes": [
                {
                    "name": "seed",
                    "type": {
                        "kind": "internal",
                        "name": "TxOutputId"
                    }
                },
                {
                    "name": "dataType",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 6,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__UpdatingDelegatedData",
            "name": "UpdatingDelegatedData",
            "fieldTypes": [
                {
                    "name": "dataType",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                },
                {
                    "name": "recId",
                    "type": {
                        "kind": "internal",
                        "name": "ByteArray"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 7,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__DeletingDelegatedData",
            "name": "DeletingDelegatedData",
            "fieldTypes": [
                {
                    "name": "dataType",
                    "type": {
                        "kind": "internal",
                        "name": "String"
                    }
                },
                {
                    "name": "recId",
                    "type": {
                        "kind": "internal",
                        "name": "ByteArray"
                    }
                }
            ]
        },
        {
            "kind": "variant",
            "tag": 8,
            "id": "__module__uutMintingDelegate__DelegateActivity[]__MultipleDelegateActivities",
            "name": "MultipleDelegateActivities",
            "fieldTypes": [
                {
                    "name": "activities",
                    "type": {
                        "kind": "list",
                        "itemType": {
                            "kind": "internal",
                            "name": "Data"
                        }
                    }
                }
            ]
        }
    ]
};
// }
