// generated by Stellar Contracts mkDataBridgeGenerator
// based on types defined in CapoMinter (src/minting/CapoMinter.hl)
// recommended: CHECK THIS FILE INTO YOUR VERSION CONTROL SYSTEM
//   ... and keep checking in the changes as your on-chain types evolve.
//
// NOTE: this file is auto-generated; do not edit directly

import { Cast } from "@helios-lang/contract-utils"
import type { UplcData } from "@helios-lang/uplc";
import type { 
    IntLike,
    ByteArrayLike,
 } from "@helios-lang/codec-utils";
import type {
    Address,
    AssetClass,
    DatumHash,
    MintingPolicyHash,
    PubKey,
    PubKeyHash,
    ScriptHash,
    SpendingCredential,
    StakingCredential,
    StakingHash,
    StakingValidatorHash,
    TimeRange,
    TxId,
    TxInput,
    TxOutput,
    TxOutputId,
    TxOutputDatum,
    ValidatorHash,
    Value,
} from "@helios-lang/ledger";
import type { EnumTypeSchema } from "@helios-lang/type-utils";


import { someDataMaker } from "../helios/dataBridge/someDataMaker.js"
import type { tagOnly } from "../helios/HeliosScriptBundle.js"
import type {hasSeed} from "../StellarContract.js"


import type {
    MinterActivity$CreatingNewSpendDelegate, MinterActivity$CreatingNewSpendDelegateLike,
    MinterActivity, MinterActivityLike
} from "./CapoMinter.typeInfo.js"

export default class mkDataBridgeCapoMinter extends someDataMaker {

    // include accessors for activity types

    // include accessors for other enums (other than datum/activity)

    // include accessors for any other structs (other than datum/activity)

    // TODO: include any utility functions defined in the contract
}

class MinterActivityHelper extends someDataMaker {
    enumCast = new Cast<
       MinterActivity,
       MinterActivityLike
   >(MinterActivitySchema, { isMainnet: true });

    mintingCharter(
        value: Address | string
    ) {
        return this.enumCast.toUplcData({ 
           mintingCharter: { owner: value } 
        }); /*SingleField enum variant*/
    }

    get mintWithDelegateAuthorizing() {
        return this.enumCast.toUplcData({ mintWithDelegateAuthorizing: {} });
    } /* tagOnly variant accessor */

    addingMintInvariant(value: hasSeed | TxOutputId | string) {
       const seedTxOutputId = "string" == typeof value ? value : this.getSeed(value);
        return this.enumCast.toUplcData({ 
           addingMintInvariant: { seed: seedTxOutputId } 
        });  /*SingleField/seeded enum variant*/
    }

    addingSpendInvariant(value: hasSeed | TxOutputId | string) {
       const seedTxOutputId = "string" == typeof value ? value : this.getSeed(value);
        return this.enumCast.toUplcData({ 
           addingSpendInvariant: { seed: seedTxOutputId } 
        });  /*SingleField/seeded enum variant*/
    }

    ForcingNewMintDelegate(value: hasSeed | TxOutputId | string) {
       const seedTxOutputId = "string" == typeof value ? value : this.getSeed(value);
        return this.enumCast.toUplcData({ 
           ForcingNewMintDelegate: { seed: seedTxOutputId } 
        });  /*SingleField/seeded enum variant*/
    }

    /**
     * generates UplcData, given a transaction-context with a seed utxo and other field details
     * @remarks
     * See the `tcxWithSeedUtxo()` method in your contract's off-chain StellarContracts subclass.     */
    CreatingNewSpendDelegate(value: hasSeed, fields: { 
        replacingUut: Option<number[]> 
    } ) : UplcData
    /**
    * generates UplcData with raw seed details included in fields.
    */
    CreatingNewSpendDelegate(fields: MinterActivity$CreatingNewSpendDelegateLike): UplcData
    CreatingNewSpendDelegate(
        seedOrUf: hasSeed | MinterActivity$CreatingNewSpendDelegateLike, 
        filteredFields?: { 
            replacingUut: Option<number[]>
    }) : UplcData {
        if (filteredFields) {
            const seedTxOutputId = this.getSeed(seedOrUf as hasSeed);
            return this.enumCast.toUplcData({
                CreatingNewSpendDelegate: { seed: seedTxOutputId, ...filteredFields } 
            });
        } else {
            const fields = seedOrUf as MinterActivity$CreatingNewSpendDelegateLike; 
            return this.enumCast.toUplcData({
                CreatingNewSpendDelegate: fields 
            });
        }
    } /*multiFieldVariant/seeded enum accessor*/ 

}


export const MinterActivitySchema : EnumTypeSchema = {
  "kind": "enum",
  "name": "MinterActivity",
  "id": "__module__CapoMintHelpers__MinterActivity[]",
  "variantTypes": [
    {
      "kind": "variant",
      "tag": 0,
      "id": "__module__CapoMintHelpers__MinterActivity[]__mintingCharter",
      "name": "mintingCharter",
      "fieldTypes": [
        {
          "name": "owner",
          "type": {
            "kind": "internal",
            "name": "Address"
          }
        }
      ]
    },
    {
      "kind": "variant",
      "tag": 1,
      "id": "__module__CapoMintHelpers__MinterActivity[]__mintWithDelegateAuthorizing",
      "name": "mintWithDelegateAuthorizing",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 2,
      "id": "__module__CapoMintHelpers__MinterActivity[]__addingMintInvariant",
      "name": "addingMintInvariant",
      "fieldTypes": [
        {
          "name": "seed",
          "type": {
            "kind": "internal",
            "name": "TxOutputId"
          }
        }
      ]
    },
    {
      "kind": "variant",
      "tag": 3,
      "id": "__module__CapoMintHelpers__MinterActivity[]__addingSpendInvariant",
      "name": "addingSpendInvariant",
      "fieldTypes": [
        {
          "name": "seed",
          "type": {
            "kind": "internal",
            "name": "TxOutputId"
          }
        }
      ]
    },
    {
      "kind": "variant",
      "tag": 4,
      "id": "__module__CapoMintHelpers__MinterActivity[]__ForcingNewMintDelegate",
      "name": "ForcingNewMintDelegate",
      "fieldTypes": [
        {
          "name": "seed",
          "type": {
            "kind": "internal",
            "name": "TxOutputId"
          }
        }
      ]
    },
    {
      "kind": "variant",
      "tag": 5,
      "id": "__module__CapoMintHelpers__MinterActivity[]__CreatingNewSpendDelegate",
      "name": "CreatingNewSpendDelegate",
      "fieldTypes": [
        {
          "name": "seed",
          "type": {
            "kind": "internal",
            "name": "TxOutputId"
          }
        },
        {
          "name": "replacingUut",
          "type": {
            "kind": "option",
            "someType": {
              "kind": "internal",
              "name": "ByteArray"
            }
          }
        }
      ]
    }
  ]
};
