// generated by StellarHeliosProject using Stellar heliosRollupTypeGen()
        
import type {CapoBundle} from "src/CapoHeliosBundle.ts"   // todo import  from @stellar-contracts
import type {HeliosScriptBundle} from "src/helios/HeliosScriptBundle.ts" // todo import from @stellar-contracts

type MinterActivity = MinterActivity
type toMinterActivity = toMinterActivity


// no datum types in this script
type CapoMinterBundleActivity = { 
    placeholderFor: "redeemer proxy or raw function type"
};

 

export default class CapoMinterBundle extends HeliosScriptBundle {
    // no datum types in this script
    Activity: CapoMinterBundleActivity    
}
