// generated by Stellar Contracts mkDataBridgeGenerator
// based on types defined in BasicDelegate (src/delegation/BasicDelegate.hl)

import { someDataMaker } from "../helios/dataBridge/someDataMaker.js"

export const test = "" // placholder for generated code
