#!/bin/bash

set -e # exit on error
#//! EXPECTS to be run in context of `pnpm exec`

tsc & 
rollup \
  --config rollup.config.ts \
  --configPlugin 'esbuild={loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}' \
  $*

wait -n
if [ $? -ne 0 ]; then
  echo "build failed"
  exit 1
fi

echo -n "build finished at "
date
# api-extractor run --local --verbose

# to debug rollup plugins:
#   pnpm exec node --inspect-brk \
#      node_modules/rollup/dist/bin/rollup \
#         --config rollup.config.ts \
#         --configPlugin 'esbuild={loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}'
