#!/usr/bin/env bash

srcDir=$(dirname $0)
. $srcDir/support.sh

WATCH="--watch"
[[ $1 == "--nowatch" ]] && {
    echo "🔍  esbuild-rollup-dev: --nowatch"
     WATCH=""
}

# note this duplicates what the main build does for building the rollup plugin
makeRollupPlugin $WATCH
sleep 0.5
echo "------------------------------ waiting ------------------------------"
wait

exitIfError
