#!/bin/bash

if [[ -z $DEBUG ]] ; then
  node node_modules/rollup/dist/bin/rollup --config rollup.config.ts \
    --importAttributesKey "with" \
      --configPlugin 'esbuild={loaders:{".json":"json"},target:"esnext",tsconfig:"./tsconfig.rollupconfig.json"}' \
  $@
#   --configPlugin 'esbuild={loaders:{".json": "json"}, target: "esnext", tsconfig:"./tsconfig.rollupconfig.json"}' \
else
    scripts/debugRollup $@
fi



