// generated by Stellar Contracts mkDataBridgeGenerator
// based on types defined in Capo (src/DefaultCapo.hl)

import { Cast } from "@helios-lang/contract-utils"
import type { UplcData } from "@helios-lang/uplc";
import type { 
    IntLike,
    ByteArrayLike,
 } from "@helios-lang/codec-utils";
import type {
    Address,
    AssetClass,
    DatumHash,
    MintingPolicyHash,
    PubKey,
    PubKeyHash,
    ScriptHash,
    SpendingCredential,
    StakingCredential,
    StakingHash,
    StakingValidatorHash,
    TimeRange,
    TxId,
    TxInput,
    TxOutput,
    TxOutputId,
    TxOutputDatum,
    ValidatorHash,
    Value,
} from "@helios-lang/ledger";
import { EnumTypeSchema } from "@helios-lang/type-utils";

import {
    RelativeDelegateLink, RelativeDelegateLinkLike,
    CapoDatum$CharterToken, CapoDatum$CharterTokenLike,
    AnyData, AnyDataLike,
    CapoDatum$DelegatedData, CapoDatum$DelegatedDataLike,
    CapoDatum, CapoDatumLike,
    CapoActivity, CapoActivityLike
} from "./CapoHeliosBundle.hlbundle.js"
import { someDataMaker } from "./helios/dataBridge/someDataMaker.js"
import { tagOnly } from "./helios/HeliosScriptBundle.js"
import {hasSeed} from "./StellarContract.js"

export default class mkDatumBridgeCapo extends someDataMaker {
    datum: CapoDatumHelper = new CapoDatumHelper(this.bundle)   // datumAccessor
    CapoDatum: CapoDatumHelper = this.datum;

    // include accessors for activity types

    // include accessors for other enums (other than datum/activity)

    // include accessors for any other structs (other than datum/activity)

    // TODO: include any utility functions defined in the contract
}

class CapoDatumHelper extends someDataMaker {
    enumCast = new Cast<
       CapoDatum,
       CapoDatumLike
   >(CapoDatumSchema, { isMainnet: true });
    CharterToken(fields: { 
        spendDelegateLink: {
    uutName: /*minStructField*/ string
    strategyName: /*minStructField*/ string
    delegateValidatorHash: /*minStructField*/ Option<ValidatorHash | string | number[]>
    config: /*minStructField*/ number[]
},
        spendInvariants: Array<{
    uutName: /*minStructField*/ string
    strategyName: /*minStructField*/ string
    delegateValidatorHash: /*minStructField*/ Option<ValidatorHash | string | number[]>
    config: /*minStructField*/ number[]
}
>,
        namedDelegates: Map<string, {
    uutName: /*minStructField*/ string
    strategyName: /*minStructField*/ string
    delegateValidatorHash: /*minStructField*/ Option<ValidatorHash | string | number[]>
    config: /*minStructField*/ number[]
}
>,
        mintDelegateLink: {
    uutName: /*minStructField*/ string
    strategyName: /*minStructField*/ string
    delegateValidatorHash: /*minStructField*/ Option<ValidatorHash | string | number[]>
    config: /*minStructField*/ number[]
},
        mintInvariants: Array<{
    uutName: /*minStructField*/ string
    strategyName: /*minStructField*/ string
    delegateValidatorHash: /*minStructField*/ Option<ValidatorHash | string | number[]>
    config: /*minStructField*/ number[]
}
>,
        govAuthorityLink: {
    uutName: /*minStructField*/ string
    strategyName: /*minStructField*/ string
    delegateValidatorHash: /*minStructField*/ Option<ValidatorHash | string | number[]>
    config: /*minStructField*/ number[]
}
    }) {
        return this.enumCast.toUplcData({
            CharterToken: fields 
        });
    }

    get ScriptReference() {
        return this.enumCast.toUplcData({ ScriptReference: {} });
    }

    DelegatedData(fields: { 
        data: {
    id: /*minStructField*/ number[]
    type: /*minStructField*/ string
},
        version: IntLike,
        otherDetails: UplcData
    }) {
        return this.enumCast.toUplcData({
            DelegatedData: fields 
        });
    }
}


class CapoActivityHelper extends someDataMaker {
    enumCast = new Cast<
       CapoActivity,
       CapoActivityLike
   >(CapoActivitySchema, { isMainnet: true });
    get usingAuthority() {
        return this.enumCast.toUplcData({ usingAuthority: {} });
    }

    get updatingCharter() {
        return this.enumCast.toUplcData({ updatingCharter: {} });
    }

    get retiringRefScript() {
        return this.enumCast.toUplcData({ retiringRefScript: {} });
    }

    get addingSpendInvariant() {
        return this.enumCast.toUplcData({ addingSpendInvariant: {} });
    }

    get spendingDelegatedDatum() {
        return this.enumCast.toUplcData({ spendingDelegatedDatum: {} });
    }

    get updatingTypeMap() {
        return this.enumCast.toUplcData({ updatingTypeMap: {} });
    }
}


export const CapoDatumSchema : EnumTypeSchema = {
  "kind": "enum",
  "name": "CapoDatum",
  "id": "__module__CapoHelpers__CapoDatum[]",
  "variantTypes": [
    {
      "kind": "variant",
      "tag": 0,
      "id": "__module__CapoHelpers__CapoDatum[]__CharterToken",
      "name": "CharterToken",
      "fieldTypes": [
        {
          "name": "spendDelegateLink",
          "type": {
            "kind": "struct",
            "format": "list",
            "id": "__module__CapoDelegateHelpers__RelativeDelegateLink[]",
            "name": "RelativeDelegateLink",
            "fieldTypes": [
              {
                "name": "uutName",
                "type": {
                  "kind": "internal",
                  "name": "String"
                }
              },
              {
                "name": "strategyName",
                "type": {
                  "kind": "internal",
                  "name": "String"
                }
              },
              {
                "name": "delegateValidatorHash",
                "type": {
                  "kind": "option",
                  "someType": {
                    "kind": "internal",
                    "name": "ValidatorHash"
                  }
                }
              },
              {
                "name": "config",
                "type": {
                  "kind": "internal",
                  "name": "ByteArray"
                }
              }
            ]
          }
        },
        {
          "name": "spendInvariants",
          "type": {
            "kind": "list",
            "itemType": {
              "kind": "struct",
              "format": "list",
              "id": "__module__CapoDelegateHelpers__RelativeDelegateLink[]",
              "name": "RelativeDelegateLink",
              "fieldTypes": [
                {
                  "name": "uutName",
                  "type": {
                    "kind": "internal",
                    "name": "String"
                  }
                },
                {
                  "name": "strategyName",
                  "type": {
                    "kind": "internal",
                    "name": "String"
                  }
                },
                {
                  "name": "delegateValidatorHash",
                  "type": {
                    "kind": "option",
                    "someType": {
                      "kind": "internal",
                      "name": "ValidatorHash"
                    }
                  }
                },
                {
                  "name": "config",
                  "type": {
                    "kind": "internal",
                    "name": "ByteArray"
                  }
                }
              ]
            }
          }
        },
        {
          "name": "namedDelegates",
          "type": {
            "kind": "map",
            "keyType": {
              "kind": "internal",
              "name": "String"
            },
            "valueType": {
              "kind": "struct",
              "format": "list",
              "id": "__module__CapoDelegateHelpers__RelativeDelegateLink[]",
              "name": "RelativeDelegateLink",
              "fieldTypes": [
                {
                  "name": "uutName",
                  "type": {
                    "kind": "internal",
                    "name": "String"
                  }
                },
                {
                  "name": "strategyName",
                  "type": {
                    "kind": "internal",
                    "name": "String"
                  }
                },
                {
                  "name": "delegateValidatorHash",
                  "type": {
                    "kind": "option",
                    "someType": {
                      "kind": "internal",
                      "name": "ValidatorHash"
                    }
                  }
                },
                {
                  "name": "config",
                  "type": {
                    "kind": "internal",
                    "name": "ByteArray"
                  }
                }
              ]
            }
          }
        },
        {
          "name": "mintDelegateLink",
          "type": {
            "kind": "struct",
            "format": "list",
            "id": "__module__CapoDelegateHelpers__RelativeDelegateLink[]",
            "name": "RelativeDelegateLink",
            "fieldTypes": [
              {
                "name": "uutName",
                "type": {
                  "kind": "internal",
                  "name": "String"
                }
              },
              {
                "name": "strategyName",
                "type": {
                  "kind": "internal",
                  "name": "String"
                }
              },
              {
                "name": "delegateValidatorHash",
                "type": {
                  "kind": "option",
                  "someType": {
                    "kind": "internal",
                    "name": "ValidatorHash"
                  }
                }
              },
              {
                "name": "config",
                "type": {
                  "kind": "internal",
                  "name": "ByteArray"
                }
              }
            ]
          }
        },
        {
          "name": "mintInvariants",
          "type": {
            "kind": "list",
            "itemType": {
              "kind": "struct",
              "format": "list",
              "id": "__module__CapoDelegateHelpers__RelativeDelegateLink[]",
              "name": "RelativeDelegateLink",
              "fieldTypes": [
                {
                  "name": "uutName",
                  "type": {
                    "kind": "internal",
                    "name": "String"
                  }
                },
                {
                  "name": "strategyName",
                  "type": {
                    "kind": "internal",
                    "name": "String"
                  }
                },
                {
                  "name": "delegateValidatorHash",
                  "type": {
                    "kind": "option",
                    "someType": {
                      "kind": "internal",
                      "name": "ValidatorHash"
                    }
                  }
                },
                {
                  "name": "config",
                  "type": {
                    "kind": "internal",
                    "name": "ByteArray"
                  }
                }
              ]
            }
          }
        },
        {
          "name": "govAuthorityLink",
          "type": {
            "kind": "struct",
            "format": "list",
            "id": "__module__CapoDelegateHelpers__RelativeDelegateLink[]",
            "name": "RelativeDelegateLink",
            "fieldTypes": [
              {
                "name": "uutName",
                "type": {
                  "kind": "internal",
                  "name": "String"
                }
              },
              {
                "name": "strategyName",
                "type": {
                  "kind": "internal",
                  "name": "String"
                }
              },
              {
                "name": "delegateValidatorHash",
                "type": {
                  "kind": "option",
                  "someType": {
                    "kind": "internal",
                    "name": "ValidatorHash"
                  }
                }
              },
              {
                "name": "config",
                "type": {
                  "kind": "internal",
                  "name": "ByteArray"
                }
              }
            ]
          }
        }
      ]
    },
    {
      "kind": "variant",
      "tag": 1,
      "id": "__module__CapoHelpers__CapoDatum[]__ScriptReference",
      "name": "ScriptReference",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 2,
      "id": "__module__CapoHelpers__CapoDatum[]__DelegatedData",
      "name": "DelegatedData",
      "fieldTypes": [
        {
          "name": "data",
          "type": {
            "kind": "struct",
            "format": "map",
            "id": "__module__StellarHeliosHelpers__AnyData[]",
            "name": "AnyData",
            "fieldTypes": [
              {
                "name": "id",
                "type": {
                  "kind": "internal",
                  "name": "ByteArray"
                },
                "key": "@id"
              },
              {
                "name": "type",
                "type": {
                  "kind": "internal",
                  "name": "String"
                },
                "key": "tpe"
              }
            ]
          }
        },
        {
          "name": "version",
          "type": {
            "kind": "internal",
            "name": "Int"
          }
        },
        {
          "name": "otherDetails",
          "type": {
            "kind": "internal",
            "name": "Data"
          }
        }
      ]
    }
  ]
};
export const CapoActivitySchema : EnumTypeSchema = {
  "kind": "enum",
  "name": "CapoActivity",
  "id": "__module__CapoHelpers__CapoActivity[]",
  "variantTypes": [
    {
      "kind": "variant",
      "tag": 0,
      "id": "__module__CapoHelpers__CapoActivity[]__usingAuthority",
      "name": "usingAuthority",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 1,
      "id": "__module__CapoHelpers__CapoActivity[]__updatingCharter",
      "name": "updatingCharter",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 2,
      "id": "__module__CapoHelpers__CapoActivity[]__retiringRefScript",
      "name": "retiringRefScript",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 3,
      "id": "__module__CapoHelpers__CapoActivity[]__addingSpendInvariant",
      "name": "addingSpendInvariant",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 4,
      "id": "__module__CapoHelpers__CapoActivity[]__spendingDelegatedDatum",
      "name": "spendingDelegatedDatum",
      "fieldTypes": []
    },
    {
      "kind": "variant",
      "tag": 5,
      "id": "__module__CapoHelpers__CapoActivity[]__updatingTypeMap",
      "name": "updatingTypeMap",
      "fieldTypes": []
    }
  ]
};
