// generated by Stellar Contracts mkDataBridgeGenerator
// based on types defined in Capo (src/DefaultCapo.hl)

import { someDataMaker } from "helios/dataBridge/someDataMaker.js"

export const test = "" // placholder for generated code
